- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt lunar-pgdg main"
    state: present
    filename: 'pgdg'

- name: Import PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update apt and install PostgreSQL 17
  apt:
    name: postgresql-17
    update_cache: yes
    state: present
